### ISSUE TITLE
Magic Eden not installed.

### ISSUE THREAD

**Issue by Shadadow** [ordzaar/ord-connect#235]
I am unable to get ord-connect to recognize Magic Eden wallet. 

After following the steps to installing, when I click on "CONNECT" and then "MAGIC EDEN" it states in console "Magic Eden not installed."

Steps to install:

# git clone https://github.com/ordzaar/ord-connect.git
# cd ord-connect
# cd packages/ord-connect
# pnpm install @ordzaar/ord-connect
# pnpm install
# pnpm dev --host

The server launches without error and is accessible on port 5173:

11:37:36 PM [vite] warning:
/usr/src/ord-connect/packages/ord-connect/src/components/PreConnectButton/index.tsx
  12:5  warning  A control must be associated with a text label  jsx-a11y/control-has-associated-label

✖ 1 problem (0 errors, 1 warning)

  Plugin: vite-plugin-eslint
  File: /usr/src/ord-connect/packages/ord-connect/src/components/PreConnectButton/index.tsx

Console log:

@ordzaar_ordit-sdk_m…n.js?v=b4b7dd38:216 Uncaught (in promise) BrowserWalletNotInstalledError: Magic Eden not installed.
    at s (@ordzaar_ordit-sdk_m…s?v=b4b7dd38:216:11)
    at r (@ordzaar_ordit-sdk_m…s?v=b4b7dd38:222:19)
    at E (@ordzaar_ordit-sdk_m…js?v=b4b7dd38:226:8)
    at index.tsx:92:40
    at WalletButton.tsx:53:7
    at HTMLUnknownElement.callCallback2 (chunk-CX6BDWJM.js?v=b4b7dd38:11102:22)
    at Object.invokeGuardedCallbackDev (chunk-CX6BDWJM.js?v=b4b7dd38:11127:24)
    at invokeGuardedCallback (chunk-CX6BDWJM.js?v=b4b7dd38:11161:39)
    at invokeGuardedCallbackAndCatchFirstError (chunk-CX6BDWJM.js?v=b4b7dd38:11164:33)
    at executeDispatch (chunk-CX6BDWJM.js?v=b4b7dd38:14444:11)
﻿
Any help would be greatly appreciated!

**Comment by Shadadow** [comment]
Resolved.
